### ISSUE TITLE
ChatGPT 4o BATCH MODE

### ISSUE THREAD

**Issue by maurobotta** [Code4Delphi/Delphi-AI-Developer#5]
Add suport for ChatGPT 4o - BATCH MODE -

https://platform.openai.com/docs/guides/batch

Tnx           :)

**Comment by Cesar4D** [comment]
Hello Mauro. ChatGPT's Batch API service is ideal for processing tasks that do not require immediate responses. It works asynchronously. This is not interesting for the Plugin, since we need immediate responses that are processed synchronously.
For these reasons, I believe that for now it is not interesting to have the Batch API developed.
I appreciate your suggestion, and if you have any tips on where to use this feature in the Plugin, please reopen this Issue.
